---
name: CI - Check Workflows

on:
  push:
    branches: [main]
    paths: [.github/workflows/**]
  pull_request:
    branches: [main]
    paths: [.github/workflows/**]
    types: [opened, synchronize]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  pull-requests: write

jobs:
  yaml-lint:
    name: YAML Lint
    runs-on: ubuntu-24.04
    timeout-minutes: 5
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Run YAML Lint in PR
        uses: reviewdog/action-yamllint@v1
        if: ${{ github.event_name == 'pull_request' && !contains(github.ref, 'renovate') }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-check
          yamllint_flags: "-c .github/config/.yamllint.yaml ."
      - name: Run YAML Lint in Branch
        uses: reviewdog/action-yamllint@v1
        if: ${{ github.event_name != 'pull_request' && !contains(github.ref, 'renovate') }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-check
          yamllint_flags: "-c .github/config/.yamllint.yaml ."
